#!/bin/bash

BRIGHTNESS_PATH='/sys/class/backlight/acpi_video0/brightness'
MAXBRIGHTNESS=$(cat /sys/class/backlight/acpi_video0/max_brightness)
MINBRIGHTNESS=1
NUMBER=$1
#Check if integer
Int='^[0-9]+$'
if [[ $NUMBER =~ $Int ]]; then
    if (( "$NUMBER" >= "$MAXBRIGHTNESS" )); then
        NUMBER=$MAXBRIGHTNESS
    elif (( "$NUMBER" < "$MAXBRIGHTNESS" )); then
        NUMBER=$MINBRIGHTNESS
    fi
    if [[ "$USER" = "root" ]]; then
        echo $NUMBER > $BRIGHTNESS_PATH
    else
        echo "Run as root, use sudo"
    fi
fi
echo "Now the brightness is $(cat $BRIGHTNESS_PATH)"
